### ISSUE TITLE
bootCoordinator URL

### ISSUE THREAD

**Issue by ed255** [hermeznetwork/contracts#13]
As far as I know, there's no way to obtain the bootCoordinator URL.  But clients need it in order to send l2txs when a slot hasn't been bid.
I think it would be interesting to have the bootCoordinatorURL as a public variable, with an associated event when it's updated.

**Comment by invocamanman** [comment]
added in https://github.com/hermeznetwork/contracts/pull/31 
The event `NewBootCoordinator` now also includes the `bootCoordinatorURL`
