### ISSUE TITLE
Set global variable: MAX_FEE_TX

### ISSUE THREAD

**Issue by krlosMata** [hermeznetwork/contracts#34]
I think it would be better to set up a global variable `MAX_FEE_TX` which determines the total number of fee transactions that the protocol can handle. It is directly related with the length of `idx` where the coordinator could receive the accumulated fees.

The first version sets this number to 64 fee transactions as it is coded in the next line: https://github.com/hermeznetwork/contracts/blob/master/contracts/hermez/Hermez.sol#L894 

I think we should make this parameter a global variable in the contract as it is done with `_MAX_L1_TX`.

**Comment by krlosMata** [comment]
I think that also `_MAX_L1_USER_TX` and `_MAX_L1_TX` should be set as `public` since they provide information for the coordinator at the time to forge batches. If those values are hardcoded across all protocols it will be fine to have them as non-public variables, but if eventually in any future version we can add more L1 user transactions, we should made them public.

**Comment by invocamanman** [comment]
I think that's good to mitigate the "magic numbers", maybe the constant could be called something like `MAX_FEE_IDX` or something like that?

And this constants should be public? it's a waste of gas in the deployment i think, these variables are constants and only could be changed if the smart contract was upgraded ( and even then, we must rename them, im pretty sure that we can't change any constant) so i don't agree in this part.

**Comment by krlosMata** [comment]
Finally variables are constants
