### ISSUE TITLE
Define a event criteria

### ISSUE THREAD

**Issue by invocamanman** [hermeznetwork/contracts#8]
There should be a consistent criteria for using or not events.
Right now, some events are necessary in order to synchronize and forge blocks as: 
` event ForgeBatch`
` event L1UserTxEvent`

Others like `event UpdateFeeAddToken` are only usefull to track all previous changes.
But not all the state variables that can be updated have and event to notify them.
So there's 2 options:
- Emit events only when are necessary in order to synchronize and forge blocks 
- Also add events for every state variable that can be update

**Comment by eduadiez** [comment]
I've created the PR #14 adding some events as a result of the TOB audit. For now they are:

* Hermez (InstantWithdrawManager.sol) -> UpdateWithdrawalDelay
* Hermez (InstantWithdrawManager.sol) -> UpdateBucketsParameters
* Hermez (InstantWithdrawManager.sol) -> UpdateTokenExchange
* Hermez (InstantWithdrawManager.sol) -> SafeMode

If @arnaubennassar @ed255 @krlosMata you think there are some other missing events or want to change some of them, I can add them to this PR.

**Comment by eduadiez** [comment]
We need to add the new `hashGlobalInputs` to the event

**Comment by ed255** [comment]
> I've created the PR #14 adding some events as a result of the TOB audit. For now they are:
> 
>     * Hermez (InstantWithdrawManager.sol) -> UpdateWithdrawalDelay
> 
>     * Hermez (InstantWithdrawManager.sol) -> UpdateBucketsParameters
> 
>     * Hermez (InstantWithdrawManager.sol) -> UpdateTokenExchange
> 
>     * Hermez (InstantWithdrawManager.sol) -> SafeMode
> 
> 
> If @arnaubennassar @ed255 @krlosMata you think there are some other missing events or want to change some of them, I can add them to this PR.

The two events that I was missing were about WithdrawalDelay and Buckets.  I see in the PR that now there are events for those two.  Nevertheless I think the event for buckets could be extended! I'll leave a comment in the PR explaining this.
